### ISSUE TITLE
Dependent bindings problem

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#109]
Since all of the bindings are simply wrapped around the final expression https://github.com/rexim/Morganey/wiki/Execution-Mode-Semantic#term-compilation-and-execution it's not clear how to make them dependent on each other and how should it work semantically. We need to research that.

**Comment by rexim** [comment]
We can [Top Sort](https://en.wikipedia.org/wiki/Topological_sorting) them though. But it doesn't allow recursive bindings anyway.

**Comment by rexim** [comment]
Do we even need recursive bindings? I mean in pure Untyped Lambda Calculus there is no any recursion. It's usually achived via the Y-combinator.

**Comment by ForNeVeR** [comment]
I think that's okay to require explicit application of Y-combinator from our users.

**Comment by rexim** [comment]
>  I think that's okay to require explicit application of Y-combinator from our users.

Yeah, I like this idea too. I was thinking about transforming recursive bindings into code that uses Y-combinators during the compilation, but it seems too complicated for now.

We can simply forbid any cyclic binding dependencies (which allows us top-sort them before wrapping them over the entry point) and ask user to explicitly use Y-combinators.

**Comment by rexim** [comment]
We also need to make sure that this REPL too

```
λ> a := 1
λ> b := a
λ> a
number: 1
λ> b
term: a
```

**Comment by rexim** [comment]
https://github.com/rexim/Morganey/blob/e7b8dcd39e6f38ef5b97d407af188edf9aac29af/kernel/src/main/scala/me/rexim/morganey/ast/LambdaTerm.scala#L12

I just realized that this filtering of unused bindings screws up the transitive bindings!!1

**Comment by rexim** [comment]
Ok, I think the problem is understood more or less well. We simply don't filter bindings in advance and toplogically sort them before wrapping over an expression. In the scope of this issue I already fixed the filtering problem. For topsort I'll create a separete ticket.
