### ISSUE TITLE
Better label system for issue tracker

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#113]
I like how NixOS utilizes GitHub issue labels: https://github.com/nixos/nixpkgs/labels They are trying to emulate fields from the normal issue trackers:
- `0.kind`
- `1.severity`
- `2.status`
- `3.skill`
- `6.topic`
- `etc.`

I want to adapt such system for Morganey. In the scope of this issue I will prepare the set of fields, possible field values and instructions in which situations they have to be used. All the artifacts of this issue are going to be published in wiki.

Wanna do that after wiki platform switch. So this issue is blocked by #107

**Comment by ForNeVeR** [comment]
For some reason they're missing 7.

**Comment by rexim** [comment]
I think it's a secret field! For secret purposes!

**Comment by keddelzz** [comment]
To be honest, I don't see the benefit of adapting the idea of NixOS' labels. But If you want to change the label system, I won't protest :)

**Comment by ForNeVeR** [comment]
I think @rexim wants to experiment with GitHub issues to see if they can be made more usable by any means. I am interested in this experiment too (because we have a huge backlog of open-source projects and it's always good to know the current state of the issues there). So if @rexim wants to, I vote for that experiment.

**Comment by keddelzz** [comment]
Thank you @ForNeVeR for your explanation. I didn't know that the changing of the label names will an experiment.

**Comment by rexim** [comment]
Ah, @ForNeVeR knows me really well :D It's actually true. Ideally I want to come with an approach that is usable across all of the [Codingteam projects](https://github.com/codingteam/)

**Comment by rexim** [comment]
Moving this issue to the `community` project: https://github.com/morganey-lang/community/issues/21 I believe it should a part of dev process guidelines.
