### ISSUE TITLE
Update sbt version

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#116]
Why is Morganey [configured to use](https://github.com/rexim/Morganey/blob/master/project/build.properties#L1) an old sbt version to build? Is this particular version required?
## 

Proposed fixes:
- We could configure it to use the latest version (`sbt.version = 0.13.12`).  
  or
- Deleting the file `build.properties` will result in sbt always using the latest version.

**Comment by rexim** [comment]
Accepted.

> Is this particular version required?

Don't think so. Probably just googled and copypasted something :D

**Comment by rexim** [comment]
Or probably it was autogenerated by Intellij IDEA! Yeah, definetly. Looks pretty IDEA-ish.

**Comment by ForNeVeR** [comment]
I think that it's always good to define versions of _everything_: Scala, sbt, every library used. So I vote against deleting `build.properties`, but it's totally ok to update the sbt version there.

It helps us to build application if the user have some older version installed. Sbt launcher will download and execute the right version the application is guaranteed to work with.

**Comment by keddelzz** [comment]
@ForNeVeR Good point!
