### ISSUE TITLE
Morganey way ranges

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#120]
Derived from https://github.com/rexim/Morganey/pull/117#discussion_r75447348

**Comment by keddelzz** [comment]
This issue was split into:
- [x] #201: Extend parser to support non-literal range literals
- [x] #202: Implement functions to construct ranges

## 

Can this issue be closed, or does #204 also count as a sub-task of #120?

**Comment by rexim** [comment]
@keddelzz yeah, I think #120 can be closed now. Thanks!
