### ISSUE TITLE
Term shorter syntax pretty-printer

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#128]
Derived from https://github.com/rexim/Morganey/pull/122#issuecomment-241213221

**Comment by keddelzz** [comment]
Is this not equivalent with #126? Both require a new implementation of the pretty-printer for lambda terms.

**Comment by rexim** [comment]
The scope of #126 is actually really small:

> enclose chars in single quotes and strings in double quotes

Because right now they are not enclosed with quotes and I cannot copy-paste them back to the input without any editing. It has nothing to do with the term pretty printer. :)

But the scope of this one is actually implementing the term shorter syntax pretty printer. Maybe a title is a bit confusing. Let me change it.
