### ISSUE TITLE
Shorter syntax usability problem

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#143]
After using the shorter syntax for a while I found a problem that was not visible during the design time. This problem comes from the fact that we use the same character for separating function arguments and its body and function arguments from each other. For example,

```
\x.y. x => (\x . (\y . x))
\x.y x  => (\x . (y x))
```

Maybe it's just me I dunno, but sometimes I simply forget that last dot and it completly changes the entire meaning of my expression. I want to address that. One of the possible solutions would be simply use different symbols for arguments and body separation, like

```
\x,y. x => (\x . (\y . x))
\x,y x => Syntax error
```

**Comment by rexim** [comment]
But overall I like the new syntax. It really helps with constructing complex terms. :)

**Comment by keddelzz** [comment]
I'm not sure if I like the proposed notation `\x,y. x`. The `,` seems more similar to a parameter separator of a c like programming language, but the current notation is more common for lambda-calculus. (See: [Wikipedia - Lambda calculus - Notation](https://en.wikipedia.org/wiki/Lambda_calculus#Notation))

Maybe it helps to think "a dot after each parameter" instead of "a dot separates parameters from function body".

**Comment by rexim** [comment]
Ok, let me use it for more time and I'll get back to this discussion with the feedback later. Maybe it's really just me.

**Comment by rexim** [comment]
A few more comments from my side

> The `,` seems more similar to a parameter separator of a c like programming language, but the current notation is more common for lambda-calculus.

It's not about comma, it's about using a different symbol for a different purpose. Just want to be clear on that. We can still use dot, but the last dot replace with arrow `\x.y -> x`. It doesn't matter.

> Maybe it helps to think "a dot after each parameter" instead of "a dot separates parameters from function body".

Notation on the wiki page has fundamentally different property which I actually like:

```
λx.λy.λz.N -> (λx. (λy . (λz . N)))
λx.λy.λz N -> Syntax error
```

You just can't write it incorrectly.

And again, I'm gonna use the current syntax a bit longer. Maybe later I'll have a different view on that. Thanks!

**Comment by rexim** [comment]
@keddelzz, I think you was right. Not experiencing this problem anymore. Thanks!
