### ISSUE TITLE
Shorter file extension

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#147]
`.morganey` is actually pretty long extension and I got pointed that out several times on the stream. Maybe we need a shorter one.

**Suggest and vote with comment**

**Comment by ghost** [comment]
Cool

**Comment by ghost** [comment]
- `.my`

**Comment by ghost** [comment]
- `.mrg`

**Comment by ForNeVeR** [comment]
`.mgn` :+1:

**Comment by keddelzz** [comment]
Another suggestion: `mgy`
(But I don't vote for that)
But I don't really care what Morganeys real file-extension will be in the future, just not longer as 4 letters is my only wish :)

**Comment by rexim** [comment]
`.mrgny`

**Comment by rexim** [comment]
`.mogny`

**Comment by rexim** [comment]
`.moy`

**Comment by ghost** [comment]
`* .mog`

**Comment by rexim** [comment]
Poll is closed. `.mgn` is the winner!
