### ISSUE TITLE
Add REPL command that lets you print the raw term (without term detection)

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#157]
`raw <term>` could print Morganeys representation without auto detection of numbers, characters and lists.

```
> raw [1,2,3]
```

could print

```
\x.x (\f.x.f x) (\x.x (\f.x.f (f x)) (\x.x (\f.x.f (f (f x))) \f.x.x))
```

instead of

```
[1,2,3]
```
## 

The exact name of this command is also up for debate.

**Comment by rexim** [comment]
I approve this proposal. Maybe in the future we will have more of such commands. For example `number 'a'` to show the number representation of the character. :) But this is already a different scope.
