### ISSUE TITLE
Common interface for REPL commands

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#159]
Since more and more commands are added to Morganey, I want you to ask how the interface should work look like and how commands will interact with the REPL. Currently the behavior of the commands is implemented [in file `Main.scala`](https://github.com/rexim/Morganey/blob/master/src/main/scala/me/rexim/morganey/Main.scala#L76). Because more commands will be added in the future this list will grow. Separation of the commands into a list or a map (as already mentioned in [93-comment](https://github.com/rexim/Morganey/issues/83#issuecomment-238098288)) could help with readability and will allow to implement #87. How should the command system evolve in the future?
## 

In difference to the currently implemented commands (`reset` and `exit`) some future commands (#149, #157 and [157-comment](https://github.com/rexim/Morganey/issues/157#issuecomment-243045159)) will have arguments.

Should we define a common interface for commands, both with and without arguments similar to [horta-hell](https://github.com/codingteam/horta-hell#command-system)? How should it look like?
## 

@rexim @ForNeVeR Your ideas are appreciated :)

**Comment by ForNeVeR** [comment]
I could only recommend you to keep in mind that one day in future we'll want to call the commands through API (for editor or server integration). So, well, probably it's not the most future-proof way to add them to some block in `Main.scala`.

**Comment by rexim** [comment]
I dunno how it's gonna evolve. Let's keep adding commands and see. I'm ok with extracting commands into a map.

**Comment by rexim** [comment]
Is this question still actual? Can we close it?
