### ISSUE TITLE
Unexpected autocompletion suggestions

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#173]
### Steps to reproduce
- Have a couple of bindings with the same prefix:

```
λ> isa := 1
λ> isb := 2
```
- Type the following:

```
λ> (isa
```
- And press TAB to autocomplete
### Observed

```
λ> (i                               // <- sa was removed here
(iisb   (isa    
λ> (i
```
### Expected

```
λ> (isa⎵
```

**Comment by ForNeVeR** [comment]
I am not sure if it's clear what should be the correct suggestion in this case. Probably nothing? There're no names starting with `isa` except `isa` itself, right?

**Comment by rexim** [comment]
This issue was really hard to describe in a ticket. I did my best. I expect whoever's gonna work on this one to just follow the instructions and see that themselves. The misbehaviour is pretty obvious. It's like porn. You'll know it when you see it.
