### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#18]

**Comment by rexim** [comment]
Was suggested by Mr @ForNeVeR

**Comment by rexim** [comment]
Let's call it Morgan. =3

**Comment by ForNeVeR** [comment]
That's much nicer.

**Comment by rexim** [comment]
`Morgan` is quite popular name for projects: https://github.com/search?utf8=%E2%9C%93&q=morgan&type=Repositories

Don't think we should take it as it is. Maybe modify a bit. Something like `MorganY`. Could be pronounced like `morgany` or like `morgan why`. The last `Y` could stand for Y-combinator or something.

https://github.com/search?utf8=%E2%9C%93&q=morgany&type=Repositories

**Comment by ForNeVeR** [comment]
Or maybe Morgana? It will be shown before "Morgany" in any alphabet-based list, and simply sounds better IMO.

**Comment by rexim** [comment]
But there are so many Morganas already on github...

**Comment by ForNeVeR** [comment]
Not so many as Morgans.

**Comment by ForNeVeR** [comment]
And your "Morgany" would sound as "Morganie" anyway. Like a pet name for Morgana. Hm, maybe Morganie is a better option?

**Comment by rexim** [comment]
MorganIE

**Comment by ForNeVeR** [comment]
No no NO!

**Comment by rexim** [comment]
Well, I'm ok with Morgana, I think :)

**Comment by rexim** [comment]
One more suggestion from Mr @ForNeVeR is `Morganey`

**Comment by rexim** [comment]
Let it be Morganey then!
