### ISSUE TITLE
Online REPL

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#182]
It would be cool to have a section in the Wiki which features an online REPL for trying out Morganey, like [Haskell](https://tryhaskell.org/) and [Clojure](http://www.tryclj.com/) have. 

That could be implemented by compiling Morganey to [scala.js](https://www.scala-js.org/) and running the repl in the browser locally.

**Comment by rexim** [comment]
Thanks for filing this! Good idea. I was thinking about this too some time ago.

**Comment by rexim** [comment]
Bringing the comment from #183 

We have two options:
- Compile Morganey to scala.js as suggested in the description of #182
- Make Morganey an online service with REST API as it's done for [Haskell](https://tryhaskell.org/) and [Clojure](http://www.tryclj.com/)  (they really send REST queries, it's clearlly visible in the dev tools console, http://www.tryclj.com/eval.json?expr=(%2B+1+1))

We need to figure out which approach better suits our needs.

@ForNeVeR @keddelzz what do you guys think?

**Comment by keddelzz** [comment]
I'm not sure which option better fits your needs.

## 

My thoughts on both options:
- An implementation of an online service will introduce a very clean API (REST API), but will (of course) require a server, on which the online REPL gets deployed to.
- If scala.js is used no server is needed for the implementation, but the build duration of Morganey will increase, because cross-compilation to JavaScript will add build phases.

## 

Both implementation options need basic security, to guard against infinite calculations. In most Webframeworks Futures are used to terminate the calculation. In most modern browsers Webworkers can be used to achieve the same functionality on JavaScript.

**Comment by ForNeVeR** [comment]
Some points on option 2:

> - If scala.js is used no server is needed for the implementation, but the build duration of Morganey will increase, because cross-compilation to JavaScript will add build phases.

Not necessarily. We simply shouldn't build Scala.js stuff by default because of this reason. Make a separate build target for that and that's it.

> Both implementation options need basic security, to guard against infinite calculations.

Again, not necessarily. If the malicious user wants to halt his own browser using the JavaScript we provided — well, let him to do it.

Although if we want to allow the users to share their Morganey snippets (in a way such that one user could post a code to our service and trick other users to execute it), then we probably want to somehow limit the amount of resources given to every program. Web workers seems like a nice implementation idea, and it'll be interesting to integrate them with Scala.js.

I also think that we should wrap Web Workers in Scala `Executor` implementation (something like `scala.scalajs.concurrent.JSExecutionContext.queue`? See an example [here in Keter](https://github.com/codingteam/Keter/blob/42e4efc4de41f653770c866dc3df89f77fda45bf/src/main/scala/ru/org/codingteam/keter/game/Engine.scala#L8), but keep in mind that Keter uses some older version of Scala.js).

My vote for option 2.

**Comment by keddelzz** [comment]
@kuchenkruste and I started implementing a online REPL with a REST-API. A short preview of all currently implemented features can be seen on YouTube [(see here)](https://www.youtube.com/watch?v=obYWL3QmVLA).

**Comment by ForNeVeR** [comment]
Wow! Very good job, buys!

**Comment by keddelzz** [comment]
The alpha version of the online REPL is implemented and ready for public release. The implementation heavily utilizes the changes proposed in #200, which are not merged, yet.

## 

How do we proceed with this feature?
Should I create a new repository, @rexim do you want to create one or should I push the REPL as a new subproject of Morganey?

**Comment by keddelzz** [comment]
You can find an updated preview on [YouTube](https://youtu.be/k-PT3tTHANs).

**Comment by rexim** [comment]
> The implementation heavily utilizes the changes proposed in #200, which are not merged, yet.

I'm gonna merge it soon. Sorry for the delay.

> How do we proceed with this feature?

This clearly sounds like a separate project for me. Please create a separate repo and push the project there. Then please post the link here. I'm gonna review the project and then we gonna prepare a plan on what to do next. Sounds good?

**Comment by keddelzz** [comment]
> I'm gonna merge it soon. Sorry for the delay.

I didn't want to put you under pressure :)

> This clearly sounds like a separate project for me. Please create a separate repo and push the project there. Then please post the link here. I'm gonna review the project and then we gonna prepare a plan on what to do next. Sounds good?

Ok!

**Comment by rexim** [comment]
@keddelzz, ok, I saw you published the project. Thank you very much!

Just to keep it captured in the issue tracker here is the link https://github.com/keddelzz/let-morganey-rest

It's already too late on my side, so I'm going to bed. Tomorrow I'll be busy through the day until the stream. So I won't be able to take a look into the project. Could try to set it up locally right on the stream, though. :) On Monday, I'll take a closer look into let-morganey-rest. Please expect questions (sometimes even organizational ones) in the issue tracker. Then I'll explain my future plans on Morganey and we will figure out what to do next. Thank you very much for you work!

**Comment by rexim** [comment]
Alright, I already said that on the stream, but I wanna have it captured in the issue tracker. The idea is basically to create a GitHub organization that unites the Morganey related projects and its developers.

I already created the organization @morganey-lang and invited all of the interested at the moment people:
- @keddelzz
- @ForNeVeR
- @kuchenkruste
- @06needhamt

### Draft of the Rules
- Anyone can join @morganey-lang organization as a Member
- If someone have an Open Sourced Morganey related project, they can join the organization as a Project Leader by transfering the ownership of the project to @morganey-lang. What that means:
  - The Project Leader preserves all of the legal rights on the transfered project. From the technical point of view I will make sure that after the transfering the ownership the Project Leader has enough control over their repo.
  - The Project Leader can transfer their project back. From the technical point of view I will help to do that.
  - The Project Leader continues to decide on how to organize the development process of the transfered repo.
  - The Project Leader can transfer the project to @morganey-lang completely which includes (but not limited to) transfering all of the legal rights on the project, ability to transfer the ownership of the project back, ability to organize the development process of the project. (This is required if the Project Leader cannot work on the project anymore and don't want the project to die. They simply donate the project to the organization).
  - Transfering the project gives
    - featuring the project on the morganey web-site (we probably gonna have one)
    - more contributors from the members and the neighbor projects
    - ???

I'll create a separate repo for join and project transfer requests and create PR with Draft of the Rules there for further discussion.

**Comment by rexim** [comment]
Here is the PR https://github.com/morganey-lang/requests/pull/1

**Comment by rexim** [comment]
Since we have a separate project for that I'm closing this issue.
