### ISSUE TITLE
The pretty-printer doesn't handle precedence correctly

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#188]
### Steps to reproduce

```
λ> :raw [0]
λz.z λf.x.x λf.x.x
λ> λz.z λf.x.x λf.x.x
```
### Observed

```
term: λz.z (λf.x.x λf.x.x)
```
### Expected

```
numbers: [0]
```

**Comment by keddelzz** [comment]
Instead of `\x.x (\f.x.x \f.x.x)` `[0]` should really be rendered as `\x.x (\f.x.x) (\f.x.x)`. And instead of `\x.x \f.x.x \f.x.x` the pretty-printer should show `\x.x (\f.x.x (\f.x.x))`.
