### ISSUE TITLE
Releases and versioning

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#210]
Derived from https://github.com/morganey-lang/Morganey/pull/209#issuecomment-248285758

Discussion and splitting assumed

**Comment by ForNeVeR** [comment]
You need to set up a release system (well, just start numbering versions already). After that we could upload the Morganey component JARs to jcenter to use them as a dependencies in the dependent projects.

**Comment by rexim** [comment]
We can follow that scheme http://semver.org/

**Comment by rexim** [comment]
I think the scope of this issue is exhausted: we have our [first release](https://github.com/morganey-lang/Morganey/releases/tag/0.0.1), we gonna follow http://semver.org/ scheme and the maven publishing is going to be resolved in the scope of #237
