### ISSUE TITLE
Easiest way to get raw term from Morganey code

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/Morganey#212]
Q: What is the easiest way to get the raw term from code. For example a function where you can pass Morganey code and it returns the raw code as proposed in https://github.com/morganey-lang/morganey-intellij-plugin/issues/6

**Comment by keddelzz** [comment]
The easiest way is to call the `term`-function of the parser. You can look at [the implementation of the `:raw` command](https://github.com/morganey-lang/Morganey/blob/49e37dc9505721634058bf6adbff14338daca461/src/main/scala/me/rexim/morganey/Commands.scala#L43) for reference.

**Comment by rexim** [comment]
Ah, yeah. You need to parse the string with the [LambdaTerm.term](https://github.com/morganey-lang/Morganey/blob/49e37dc9505721634058bf6adbff14338daca461/kernel/src/main/scala/me/rexim/morganey/syntax/LambdaParser.scala#L86) parser. Is this convenient enough interface for you?

**Comment by 06needhamt** [comment]
Yes that should be fine I will take a look in the morning

**Comment by 06needhamt** [comment]
This works fine i will close the issue now
