### ISSUE TITLE
Pack std-lib with fatjar version of Morganey

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#216]
Derived from https://github.com/morganey-lang/Morganey/issues/214#issuecomment-249235662
### Pieces:
- [x] #242 Pack std folder to the fatjar
- [x] #222 Develop a mechanism for discovering Morganey modules inside of zips?

---

Should the fatjar version of Morganey contain the std-lib? If not how should we distribute the std-lib?

**Answer: yes, the fatjar should contains the std-lib**

**Comment by ForNeVeR** [comment]
I think it should. Morganey users expect to be able to use the standard library, whether they use fat or tiny or über JAR.

**Comment by rexim** [comment]
@ForNeVeR @keddelzz cool! Converting this into an enhancement then!

**Comment by keddelzz** [comment]
That might allow to reuse the module path in online REPL (related issue: [let-morganey-rest#5](https://github.com/morganey-lang/let-morganey-rest/issues/5)).
