### ISSUE TITLE
Pack std-lib as a separate jar for tiny jars version of Morganey

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#218]
Derived from the discussion on the stream.

Just keep the std-lib in a separate jar `morganey-stdlib.jar`

**Comment by keddelzz** [comment]
Just to link this:

Depending on the `morganey-stdlib.jar` probably is a better solution than using the fat-jar in [let-morganey-rest#5](https://github.com/morganey-lang/let-morganey-rest/issues/5).

**Comment by keddelzz** [comment]
Just leaving my thoughts here: `ModuleFinder` might be upgraded in the scope of this issue to be able to load modules from jars (or from the java-classpath) instead of only from files.

**Comment by ForNeVeR** [comment]
I think that we just need the classpath support; there's no need to manually do the lookup in the JARs. JVM is able to manage the classpath itself (and the user can tune the classpath using the standard user-level mechanisms such as sbt).
