### ISSUE TITLE
Update 'ModuleFinder' to be able to load modules from java classpath

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#222]
Split from #216 

Brining all relevant information here:

> Just leaving my thoughts here: `ModuleFinder` might be upgraded in the scope of this issue to be able to load modules from jars (or from the java-classpath) instead of only from files.

(source: [218 keddelzz' comment](https://github.com/morganey-lang/Morganey/issues/218#issuecomment-249429687))

> I think that we just need the classpath support; there's no need to manually do the lookup in the JARs. JVM is able to manage the classpath itself (and the user can tune the classpath using the standard user-level mechanisms such as sbt).

(source: [218 ForNeVeR's comment](https://github.com/morganey-lang/Morganey/issues/218#issuecomment-249430395))
## 

This issue will allow the online REPL to reuse Morganey's module path [let-morganey-rest#5](https://github.com/morganey-lang/let-morganey-rest/issues/5).

**Comment by rexim** [comment]
This issue can potentially supersed #85

**Comment by ForNeVeR** [comment]
@rexim I think that it's definitely superseding #85.

**Comment by keddelzz** [comment]
Should the `ModuleLoader` **only** load the std-lib from zips/jars and thus replace the old implementation or do we want to add the capability to load from jars/zips?

**Comment by ForNeVeR** [comment]
@keddelzz my opinion is that we want it to _only_ load the resources from the classpath. Please note that classpath is a standard Java concept, and it may be formed from a list of directories, and either ZIP or JAR files. So, by properly setting up the classpath, Morganey user may direct Morganey to load the modules from either stdlib (or optionally disable it), any JAR or a local directory.

I believe that `.` is included in a classpath by default, so Morganey uberjar should be able to load stdlib from the current directory if ran without the additional classpath configuration (although I'm not sure that's the case; I haven't checked).

So, yeah, in my opinion, the new module loader should completely supersede the old one.

**Comment by rexim** [comment]
This issue has been split from #216.

### Pieces
- [x] #256 Add specs for ModuleFinder.findModuleInClasspath
- [x] #258 Use classpath modules in MorganeyCompiler
- [x] #257 Use classpath modules in ReplAutocompletion
