### ISSUE TITLE
Build in master is broken

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#230]
https://travis-ci.org/morganey-lang/Morganey/builds/163082405#L261

Something's wrong again on Travis side. We already experienced something similar (cannot find the link at the moment).

@rexim try to restart the build later.

**Comment by ForNeVeR** [comment]
I've restarted the build and it was okay this time. We'll probably get better Travis experience if we cache the dependencies (e.g. `~/.ivy2`) as we already did on Appveyor.

**Comment by rexim** [comment]
@ForNeVeR thanks!
