### ISSUE TITLE
Use hidden-args

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#233]
Use [hidden-args](https://github.com/keddelzz/hidden-args) to remove boilerplate of functions with an nested tail-recursive helper-function. To be able to use [hidden-args](https://github.com/keddelzz/hidden-args), two new dependencies have to be added to Morganey:
- [hidden-args](https://github.com/keddelzz/hidden-args) itself
- The compiler plugin [macroparadise](https://github.com/scalamacros/paradise)

**Comment by keddelzz** [comment]
Potential usage of [hidden-args](https://github.com/keddelzz/hidden-args):
- [here](https://github.com/morganey-lang/Morganey/blob/26ec2a2348a9bb5a2f9d28b439dccd86a732039f/kernel/src/main/scala/me/rexim/morganey/ast/LambdaTerm.scala#L81)
- [here](https://github.com/morganey-lang/Morganey/blob/26ec2a2348a9bb5a2f9d28b439dccd86a732039f/kernel/src/main/scala/me/rexim/morganey/ast/LambdaTerm.scala#L108)
- [maybe here](https://github.com/morganey-lang/Morganey/blob/26ec2a2348a9bb5a2f9d28b439dccd86a732039f/kernel/src/main/scala/me/rexim/morganey/church/ChurchNumberConverter.scala#L13)
- [maybe here](https://github.com/morganey-lang/Morganey/blob/26ec2a2348a9bb5a2f9d28b439dccd86a732039f/kernel/src/main/scala/me/rexim/morganey/church/ChurchNumberConverter.scala#L23)
- [maybe here](https://github.com/morganey-lang/Morganey/blob/26ec2a2348a9bb5a2f9d28b439dccd86a732039f/kernel/src/main/scala/me/rexim/morganey/util/package.scala#L37)

**Comment by rexim** [comment]
I like the idea, but I don't know too much about macros in scala. Could you please tell me more about the status of that macroparadise thingy? Is that an official thing? It looks like a separate plugin. What's the difference between macroparadise and regular scala macros?

Sorry for stupid questions. The google results are confusing. :)

**Comment by ForNeVeR** [comment]
I thought macroparadise is only for scala 2.10. Since 2.11 we have native macros that do the same thing. So, yeah, I'd like @keddelzz to elaborate. It seems to be interesting.

**Comment by keddelzz** [comment]
Macroparadise implemented macros and quasiquotes for scala-version <= 2.10.x.
Scala versions 2.11.x don't require macroparadise for macros and quasiquotes, because it was merged into the "native" scala compiler. However for macro annotations macroparadise is still needed. Macro annotations as well as macros themselves are still experimental features.

**Comment by ForNeVeR** [comment]
@rexim let's say it's non-official thing that uses the official compiler plugin API. So it's perfectly legal in every sense ,)

**Comment by keddelzz** [comment]
I don't know, what is planned for the upcoming scala 2.12.x release. Let's hope that macro annotations are still available :)

**Comment by rexim** [comment]
Alright, sounds good to me. Morganey was always about experimentation. :) I accept this proposal.

@keddelzz feel free to assign the issue to yourself if you wanna work on it.

Thanks!

**Comment by keddelzz** [comment]
Do you mind, if I depend on the github repository of [hidden-args](https://github.com/keddelzz/hidden-args) instead of using `publishLocal`?

**Comment by ForNeVeR** [comment]
@keddelzz it's even better to depend on GitHub. Although the best option is to publish your (excellent) work to some Maven repository such as JCenter.

For now I vote for GitHub reference.

**Comment by rexim** [comment]
Yeah, GitHub dependency is fine. :)

**Comment by keddelzz** [comment]
> your (excellent) work

Thank you very much @ForNeVeR for your compliment. :)
