### ISSUE TITLE
Morganey hangs when input is redirected on Windows

### ISSUE THREAD

**Issue by ForNeVeR** [morganey-lang/Morganey#234]
_(Extracted from #214.)_

This completely hangs on my machine (Windows 10 x64) when ran from `cmd.exe` shell:

``` console
$ sbt assembly
$ echo :exit | java -Dfile.encoding=windows-1251 -jar target\scala-2.11\morganey.jar
?>
```

I think that it should exit immediately after the start, but it just keeping showing me a `?>` prompt and not accepting any input at all. It eats 100% of one CPU core while doing that.

@rexim claims the same works okay on Linux.

**Comment by rexim** [comment]
Can be related to #231
