### ISSUE TITLE
Maven Repository For Morganey

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/Morganey#237]
With the addition of the new build system for the [IntelliJ plugin](https://github.com/morganey-lang/morganey-intellij-plugin/pull/14). a maven repository where versions of morganey JARs can be hosted would be very useful. At the moment there is a [jars](https://github.com/morganey-lang/morganey-intellij-plugin/tree/new-build/jars) Directory where jars can be placed to be accessible by the Gradle [Build System](https://github.com/morganey-lang/morganey-intellij-plugin/blob/new-build/build.gradle#L59). This is OK when there is only a few Morganey versions but when more versions are released the repository will quickly become bloated with jars.

Having a maven repository would allow the build system to pick up all released Morganey versions by their unique maven id instead of searching for it in the jars directory. Therefore less dependancies will be held in the repository and will be less prone to bugs 

@rexim @ForNeVeR @keddelzz Let me know what you think

**Comment by ForNeVeR** [comment]
Note that we already have the issue to track JAR deployment: #210.

**Comment by rexim** [comment]
This issue is a subscope of #210. So I think it's good to have it.

**Comment by rexim** [comment]
Just a useful link https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by ForNeVeR** [comment]
I still recommend to use JCenter. Maven Central involves too much bureaucracy.

**Comment by rexim** [comment]
This issue is needed for https://github.com/codingteam/horta-hell/issues/364

**Comment by rexim** [comment]
May be useful https://github.com/softprops/bintray-sbt

**Comment by rexim** [comment]
Just moving everything from #47 %)

**Comment by rexim** [comment]
Split at #259

### Remaining work
- [x] #260 Backport configuration to 0.0.1
- [x] ~#261 Publish Morganey 0.0.1 to JCenter~
- [x] ~#323 Backport 93c35c2 to 0.0.1~
- [x] ~#324 Publish Morganey 0.0.2 to JCenter~
- [x] #325 Publish 0.1.0 to JCenter
