### ISSUE TITLE
Gradle Morganey plugin

### ISSUE THREAD

**Issue by ForNeVeR** [morganey-lang/Morganey#238]
We'll probably want to create a plugin for a build system (I propose Gradle, but feel free to look at Lein or SBT) that will package the `*.mgn` files in a standard Morganey format (be it `*.jar` or `*.class` or whatever). That'll help to standartize and improve the user experience of the poor guys who chose to program in Morganey.

**Comment by rexim** [comment]
I accept that! Nice idea!

**Comment by rexim** [comment]
Could be a separate project btw

**Comment by 06needhamt** [comment]
I would like to help out on this if we end up doing it

**Comment by rexim** [comment]
I created a repo for the Morganey gradle plugin https://github.com/morganey-lang/gradle-morganey-plugin

We can start the initial discussion there.

**Comment by rexim** [comment]
Since we have a separate project for that and the initial requirements are met, I'm closing this issue.
