### ISSUE TITLE
Name fatjar properly

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#240]
Right now the generated fatjar is called just `morganey.jar`. It was done to make it easier to refer to that jar in [funtests](https://github.com/morganey-lang/Morganey/blob/d355a4e573d2a7aa8444834f2cc59cb5177792e8/funtests/src/test/scala/me/rexim/morganey/funtests/MorganeyProcess.scala#L7). Changing the version of Morganey changes the filename, which makes funtests incompilable.

We need to fix that. Maybe pass the version to funtests from the sbt side as a java property.

**Comment by keddelzz** [comment]
> Maybe pass the version to funtests from the sbt side as a java property.

https://github.com/sbt/sbt-buildinfo might help with that.

**Comment by ForNeVeR** [comment]
See also [`Build.scala`](https://github.com/codingteam/horta-hell/blob/43efcfd14cc54ed06f8b5d817fdaac4efade4e61/project/Build.scala#L31-L47) and [`VersionPlugin.scala`](https://github.com/codingteam/horta-hell/blob/43efcfd14cc54ed06f8b5d817fdaac4efade4e61/src/main/scala/ru/org/codingteam/horta/plugins/VersionPlugin.scala#L22-L24) to check how we make the project version accessible to Scala code in Horta.
