### ISSUE TITLE
Create proper sub-project for 'std'

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#242]
Split from #216 

Currently Morganey's std-lib exists in a subfolder of Morganey. This folder is manually zipped to produce the tiny-jar. This was implemented by me in the scope of #218. 

However I propose to change that: Instead of manually zipping the contents of the folder it would be a better solution to turn the std-folder in a sub-project. That would have the advantage, that the `build.sbt` file will be a cleaner and that this implements #216, because sub-projects are automatically included in the uber-jar.

**Comment by rexim** [comment]
Sounds great! Approved! :)
