### ISSUE TITLE
Support comments in scripts

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#28]

**Comment by keddelzz** [comment]
This should be very easy! Simply add comments to the whiteSpace-Parser, as described in http://stackoverflow.com/a/5954831

**Comment by rexim** [comment]
@keddelzz looks cool! Thanks for such a useful link! :)

**Comment by rexim** [comment]
Resolved by d20ce7c9244883e6834a5a0f26a0c280e8df9a21
