### ISSUE TITLE
Publish 0.1.0 to JCenter

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#325]
Subtask of #237

**Comment by rexim** [comment]
I tried to publish 0.1.0. But something's slightly off again. Nothing really serious. My brain is just shutting down and cannot perform basic operations. Gonna continue working on that tomorrow.

**Comment by ForNeVeR** [comment]
You should reinstall OS on your brain, dawg!

**Comment by rexim** [comment]
Almost all of the packages (`morganey`, `morganey-kernel`, `morganey-std`) are available via JCenter. Except `morganey-macros` for some reason. I will follow up on that one.

**Comment by rexim** [comment]
All of the packages are successfully published.
