### ISSUE TITLE
Morganey Logo

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#33]
Draw the Morganey Logo. Basically, it should look like this: `(λ o.o)`

**Comment by keddelzz** [comment]
What if the logo was just the word "Morganey" spelled with a few greek letters? For example: 
![morganey](https://cloud.githubusercontent.com/assets/3746739/16713499/ca8f9fd8-46a9-11e6-8dcf-7c31673ba983.png)

**Comment by ForNeVeR** [comment]
I am not sure whether `λ` could be read as `y` and that `η` could be read as `n`. I think that it's better to replace the letters phonetically, but overall I like the idea.

Remember, we don't want the Greek guys (ancient or otherwise, although we probably care more about the ancient ones) to laugh on our illiteracy.

**Comment by keddelzz** [comment]
Well, I agree! This was just a quick idea I've had. :)

**Comment by ForNeVeR** [comment]
My Ancient Greek approximation is `μωργᾰνῐ` (I was using [this](https://en.wikipedia.org/wiki/Help:IPA_for_Greek) phonetic translation). But probably it's too fancy, because I doubt that guys not familiar with Ancient Greek will read that as "Morganey" :crying_cat_face:

**Comment by keddelzz** [comment]
I have to confess, that after seeing the word `μωργᾰνῐ`, I would not know what the name of the project is. So maybe my ancient Greek is not good enough (or maybe I've no knowledge about the Greek alphabet at all :))

**Comment by ForNeVeR** [comment]
I agree that it's counter-intuitive in context of a "common" modern Latin alphabet interpretation, so I think we're open to suggestions.

**Comment by rexim** [comment]
What is going on here? 
![id](https://cloud.githubusercontent.com/assets/165283/16713745/dd6e4fae-46d2-11e6-9ef0-c4442b241b1d.gif)

**Comment by rexim** [comment]
@keddelzz I actually like your suggestion. Thanks! Let's keep it as an option. I'm not 100% confident about any available variant of the logo right now. So let's just keep this thread going. Maybe some day we will find something interesting. :)

**Comment by rexim** [comment]
Superseded by https://github.com/morganey-lang/community/issues/43
