### ISSUE TITLE
Set the goal for 0.2.0 release

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#334]
The goal of 0.1.0 was to deliver std-lib packed with fatjar. We delivered that. We need to set the goal for 0.2.0 now.

**Comment by rexim** [comment]
@morganey-lang if you have any preferences regarding the `0.2.0` please let me know here.

**Comment by keddelzz** [comment]
I think in `0.2.0` we should mainly work on performance improvements as well as on refactorings and bug-fixes.

Issues related to performance improvements:
- #29: Parallel reduction
- #59: Collapsed Applications
- #60: Detection of arithmetic operations
- #206: Performance improvement: Numbers

We should also complete the implementation of the Prelude mechanism (#79) in `0.2.0`.

**Comment by rexim** [comment]
@keddelzz all of the issues you've mentioned are important, but I wouldn't plan all of them for `0.2.0`, because it's much more amount of work comparing to `0.1.0`. And `0.1.0` was just a "simple" packing of std-lib with the fatjar ;)

I'm gonna plan #59, because I already tried it and found out that it may require to heavily refactor the entire codebase. Sound like enough work for a realease. Plus #79 since it should be pretty straightforward.

Thanks for the suggestions!
