### ISSUE TITLE
Make uberjar

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#45]
So we are able to use it standalone. Such jar should be not used as a thirdparty dependency.

https://github.com/sbt/sbt-assembly

**Comment by ForNeVeR** [comment]
Please note that I would prefer simple JAR as a dependency of a Horta plugin.

But maybe users of standalone Morganey version will prefer the "uberjar".

**Comment by rexim** [comment]
@ForNeVeR yes, this is correct. Uberjar is for standalone usage only. Let me put that in the description.

**Comment by rexim** [comment]
It can be also used for #55
