### ISSUE TITLE
Publish stable version for thirdparty dependencies

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#47]
Needed for https://github.com/codingteam/horta-hell/issues/364

**Comment by rexim** [comment]
https://bintray.com/ should work

**Comment by ForNeVeR** [comment]
I have an experience with using bintray, so feel free to ask if you need help.

**Comment by rexim** [comment]
Thank you very much Mr @ForNeVeR :)

**Comment by rexim** [comment]
May be useful https://github.com/softprops/bintray-sbt

**Comment by rexim** [comment]
Duplicate of #237
