### ISSUE TITLE
Nil in morganey

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#62]
I think it would be nice, of Morganey was able to express nil.

Nil (or for example []) could also be a literal for the empty list (#58).

**Comment by rexim** [comment]
Bringing some information from our other discussion. I think it's useful and I just don't wanna lose it:

Morganey is not aware of `nil` at all. We encode lists like `(a . (b . (c . d)))`. The last element of the list is the second element of the innermost pair. It's not the best solution, but it was the quickest one at the time. Using a notion of `nil` here would be probably better.

**Comment by rexim** [comment]
I think the improvement of the list format described in my previous comment should be done in the scope of this issue.
