### ISSUE TITLE
Testing macros in meta subproject on CI

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#63]
Derived from discussion: https://github.com/rexim/Morganey/pull/61#discussion_r69382326

**Comment by keddelzz** [comment]
Some relevant comment from [#61 (comment)](https://github.com/rexim/Morganey/pull/61#issuecomment-230153347):

If you want I could write more (integration) tests for macro expansion results later, but this will have to wait a bit. Maybe I could add some in the next week.

## 

I implemented the feature therefore I should be responsible for adding tests. If you want, you can assign this to me (if this is possible).

**Comment by rexim** [comment]
@keddelzz sure. I made you a collaborator. ;)

That means you can also push feature branches to this repo instead of the forked one. No need to mess with two origins. :) Hope it simplifies the process of contribution.

**Comment by keddelzz** [comment]
Nice, I was going to ask you about how contribution works :)

That will massively simplify the process!
Thank you! :D
