### ISSUE TITLE
Shorter syntax for lambda terms

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#67]
It's a bit troublesome to write and read big terms right now. (At least for me.)

I suggest to add an alternative syntax, as described in [lambda calculus - notation](https://en.wikipedia.org/wiki/Lambda_calculus#Notation) to unclutter the lambda terms a bit.

But I see a problem with the last point:

> - A sequence of abstractions is contracted: λx.λy.λz.N is abbreviated as λxyz.N

Because Morganey allows variable names longer than one letter, this abbreviation rule might has to be changed to something like:
- A sequence of abstractions is contracted: λx.λy.λz.N is abbreviated as λx.y.z.N
  So it will be at least a bit shorter.

With the alternative style there could arise ambiguity-problems with the syntax. Those have to be addressed, too.

If the lambda-terms are also rendered with the new shorter syntax, this issue also addresses #51.

**Comment by rexim** [comment]
@keddelzz, It's a nice idea, thanks! :) Was thinking about that too some time ago.
