### ISSUE TITLE
Fix detection of strings containing escape-sequences

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#68]
Simple example:

``` c
λ> "Hello\nWorld"
numbers: 72,101,108,108,111,10,87,111,114,108,100
```

Files that have to be changed:
- [ReplHelper.scala](https://github.com/rexim/Morganey/blob/master/src/main/scala/me/rexim/morganey/ReplHelper.scala)
- [ChurchNumberConverter.scala](https://github.com/rexim/Morganey/blob/master/kernel/src/main/scala/me/rexim/morganey/church/ChurchNumberConverter.scala)

**Comment by rexim** [comment]
ASCII code of ~~space~~newline is 10. It simply does not fit into our definition of a printable character.

**Comment by rexim** [comment]
Also, just a hint. When you browsing a file on GitHub you can press `y` and will transform your current URL into a permanent one with a commit hash. It will look like this: https://github.com/rexim/Morganey/blob/8e7ed9f3a4f21bc4e3f554a456f75cbec4fa1cc4/kernel/src/main/scala/me/rexim/morganey/church/ChurchNumberConverter.scala

It is better to use permanent URLs in issues and comments. [ReplHelper.scala](https://github.com/rexim/Morganey/blob/master/src/main/scala/me/rexim/morganey/ReplHelper.scala) doesn't exist anymore. :)

**Comment by ForNeVeR** [comment]
> ASCII code of space is 10.

You mean for newline, right? Because it's 0x20 for space.

> When you browsing a file on GitHub you can press 'y' and will transform your current URL into a permanent one with a commit hash.

OH MY GOD THANK YOU.

Really, I wasn't aware of this feature and was damned to make these URIs in a hard way.

**Comment by rexim** [comment]
> You mean for newline, right? Because it's 0x20 for space.

Right. Thank you!

> Really, I wasn't aware of this feature and was damned to make these URIs in a hard way.

You're welcome! :)

**Comment by keddelzz** [comment]
> Also, just a hint. When you browsing a file on GitHub you can press y and will transform your current URL into a permanent one with a commit hash.

`y` is not working for me. :(

**Comment by rexim** [comment]
> `y` is not working for me. :(

This is strange. Try also `?`. It shows all of the available shortcuts on the current page

**Comment by keddelzz** [comment]
> y is not working for me. :(

It's working now, thank you! Also thanks for giving a hint to such a useful feature!

**Comment by keddelzz** [comment]
Should we add the escape-sequences, [the language knows about](https://github.com/rexim/Morganey/blob/8e7ed9f3a4f21bc4e3f554a456f75cbec4fa1cc4/kernel/src/main/scala/me/rexim/morganey/syntax/Language.scala#L9), to the set of printable characters?

**Comment by rexim** [comment]
Yeah, I think that's the solution for this bug. :)

**Comment by keddelzz** [comment]
> Yeah, I think that's the solution for this bug. :)

Yes.

> Should we add the escape-sequences, the language knows about, to the set of printable characters?

... but this question should really mean "Do you guys think that'a bug, or is the behavior in the description of this issue intended?"

**Comment by rexim** [comment]
> Do you guys think that'a bug, or is the behavior in the description of this issue intended?

Ah, yeah! That's a better question!

I checked the Internets. They say ~~space~~newline is not a printable character. :( http://www.ascii-code.com/ It is so called control character.

I cannot answer this question right now. It depends on how Morganey IO will evolve in the future. I will think about that and try to answer later. Thanks for the question!

**Comment by rexim** [comment]
If we want to be able to write more or less useful programs in Morganey we have to be able to output arbitrary things on stdout without Smart Church Detection™. I see some kind of special mode for execution where `main` returns list of numbers and those numbers are printed literally as ASCII codes to stdout. That will enable us with outputing anything as long as it's expressible in Pure Untyped Lambda Calculus. I don't have any robust design for this idea yet, I'll create the issue later. Anyway I don't consider this a bug anymore. Rather an inteded behaviour if Smart Church Detection™ is enabled.
