### ISSUE TITLE
Autocomplete in REPL

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#70]
It would be cool to be able to tab autocomplete vars form the global context.

**Comment by keddelzz** [comment]
Basic functionality implemented in c6a765c, but I want to add autocompletion for module-paths in load-statements as well :) I'll create a PR, as soon as I've implemented it!

**Comment by rexim** [comment]
@keddelzz wow! That is so cool! Looking forward to review that. :)

**Comment by keddelzz** [comment]
Autocompletion for paths in load statements is implemented with 08c69ce. I'll add some unit-tests (hopefully) later today, then I'll create a pull request.

**Comment by rexim** [comment]
Sure, take your time! :)
