### ISSUE TITLE
Extensible standard library / module system

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#73]
It would be nice, if Morganey knew some basic operations like `succ`, `pred`, `id`, `first`, `second`... Therefore I suggest the implementation of a standard library, which can be extended by the user of morganey.

My idea is, that there's a folder somewhere on the computer where you can add morganey-source-files and they are automatically loaded into each REPL-session and as a library for each program.

Instead of being loaded automatically the modules could also be loaded via an import/include statement.

**Comment by rexim** [comment]
This is a great idea! I completely agree that we need a standard library. I currently formalizing how I see the idea. I'm gonna post my vision as soon as possible (probably in a couple of hours or so) and we can discuss everything. :)

**Comment by rexim** [comment]
Alright, this is my vision of the Morganey Module System. I'd like to go with the common for most of the languages approach.

# Morganey Module System

## Module

We introduce a notion of a module. A module is a separate script file with a bunch of Morganey bindings.

## Module Path

We introduce a notion of the Module Path. It is similar to the Java's Class Path. Basically the place where Morganey Interpreter searches for its modules. It can be an environment variable containing paths separated by `;`-s or a command line flag. The exact mechanisms can be discussed separately.

## Module Loading

We introduce a load expression to the language. The expression has approximately the following syntax:

``` bnf
<load-expression> ::= load <module-path>
<module-path> := <relative-path-to-module-file-without-extension>
```

Usage example:

``` morganey
load math/arithmetic
load pair

x := ((succ 5) 6)
```

The final syntax can be discussed separately.

When the Morganey Interpreter encounters a load expression it searches for the module file according to the Module Path and interprets the file as it would interpret any other Morganey script adding all of the bindings from the module file to the global context and continues the execution.

With such definition of the loading we will have a problem of cycled loads. We can try to remember what modules were loaded and simply do not load them more than once.

## Standard Library

We introduce the standard library. The standard library is a bunch Morganey modules organized in a hierarchy. The modules in the standard library are in the Module Path by default, so the user can load them in the REPL or a script. The exact modules, their hierarchy and locations can be discussed separately.

## Prelude

We introduce a notion of Prelude. It is similar to the Haskell's Prelude. Prelude is a module that is always loaded automatically when the Morganey session starts. This module usually contains a bunch of other module loads from the standard library. We can put all of the common operations like `succ`, `pred`, `id`, `first`, `second`, etc, there. The exact module to load from Prelude, and the Prelude location can be discussed separately.

---

@keddelzz, what do you think?

Also if I understood you correctly you suggest to allow the user to modify what I called above Prelude. I don't actually think it's essential to allow the user to modify it. If they want something besides standard library they can put that to a separate module, add that module to the Module Path and just load it from their script or REPL. I believe this is a pretty common approach in most of the programming languages.

**Comment by keddelzz** [comment]
Your ideas are basically what I dream to have in Morganey. I would not like modifying environment variables for changing the morganey-path, so I suggest using commandline flags.

My first idea was just to have a single directory where you can put files, which are automatically loaded into scripts and the repl. Your approach is much more evolved than mine. With the use of general modules my suggestion (modifying the Prelude) is obsolete.

**Comment by rexim** [comment]
@keddelzz, cool! Glad that you like it. :) It doesn't look to difficult for me to implement the entire idea. Don't you mind if I take this issue and plan it for tomorrow's stream?

**Comment by rexim** [comment]
If you wanted to implement this by yourself it's ok. I can pick something else. :)

**Comment by keddelzz** [comment]
No of course you can implement it tomorrow! After all, it's your project.

**Comment by rexim** [comment]
Cool! Thank you! :)

**Comment by rexim** [comment]
Exausted the scope of this issue. Thus closed.
