### ISSUE TITLE
Emacs major mode for editing Morganey files

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#81]
We can put it to this repo for now (MELPA can package files from repos selectively). If it gets anywhere, we will move it to a separate repo.

The scope of this issue
- Hightlight keywords: `λ`, `load`
- Hightlight strings and chars
- Hightlight comments
- Support for commenting regions (`comment-dwim`, etc)

**Comment by keddelzz** [comment]
It would be nice, if the parser was not reimplemented in another language. Maybe the major emacs mode could communicate with an instance of the Morganey-compiler, which is run as a separate process, over the network. (The same way ENSIME is integrated in emacs.)

**Comment by rexim** [comment]
@keddelzz, yep, sounds like a good idea. Honestly, I wouldn't do it for the syntax highlight ('cause if you want to edit a couple of lines starting a fat JVM process is a bit tedious IMO). But for semantic hightlight (like ENSANE hightlights implicit stuff), autocompletion and navigation I would totally use that approach. Thanks!

**Comment by rexim** [comment]
And regarding the syntax hightlight, I doubt that a usable hightlight will require more than defining a couple of keywords. We don't need the entire BNF definition for that. So I wouldn't worry about a separate process just for the syntax hightlight. But for everything else, yes, a separate process would be useful.

**Comment by keddelzz** [comment]
What exactly do you plan on implementing in the scope of this issue? Just a syntax highlighter or also autocompletion and navigation?

**Comment by rexim** [comment]
@keddelzz Right, I didn't realize that this issue has a vague scope! Thanks! I plan to implement basic syntax highlight and indentation. Just something to start with. And everything else is gonna separate issues. Let me put that in the description...

**Comment by rexim** [comment]
Done. Decided not to put indentation to the scope of this issue. Don't actually know what is a sufficient solution for that yet. I better make it a separate issue later.

**Comment by rexim** [comment]
Btw, Mr @ForNeVeR made https://github.com/ForNeVeR/cil-mode a while ago. It can be used as a reference here, I guess.

**Comment by keddelzz** [comment]
I think this title is misleading now, because script semantic was removed in #176.
Should I rename it to "Emacs major mode for editing Morganey files" or Emacs major mode for editing Morganey modules"?

**Comment by rexim** [comment]
Done! :)

**Comment by rexim** [comment]
Moved to https://github.com/morganey-lang/morganey-mode
