### ISSUE TITLE
Morganey Program Execution Semantic and Side-effects

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#82]
During my work on #77 I faced the problem that we don't have formalized the Morganey Program Execution Semantic and its Side-effects. Which actually makes the implementation of the Morganey Interpreter pretty weird and hard to maintain.

On the stream @keddelzz suggested to implement some sort an entry point binding. For some reason I didn't like the idea at first, but after thinking about it for a while, I think it's actually pretty good! So I've tried to more or less formalize all of that and here is my vision of the Morganey Program Execution Semantic and how the side-effects are made.

Please share your thoughts.
# Morganey Program Semantic
## Morganey Module

Morganey Module is a file that consists of only bindings or loadings. No free terms.

Example:

``` morganey
// numbers.morganey

load math.arithmetic

six := (succ 5)
ten := ((plus 5) 5)
```
## Entry Point

Entry Point is a special binding inside of a Morganey module that has a special name (let it be `main`). This special name should be bound to a function that takes one argument.

Example:

``` morganey
// main.morganey

load math.arithmetic

main := (\input . <...>)
```
## Input Stream

Input Stream, it's a lazy evaluating Church pair encoded list of Church encoded numbers. This Stream represents the Standard Input of the program. The Morganey interpreter is responsible for constructing this list on the fly. The Morganey program can access this Stream only via argument of the Entry Point.
### Load Graph

When the Morganey Interpreter is given a file with a program to execute, it starts with building a Load Graph beginning from the file. A Load Graph is graph where vertices are Morganey Modules and the edges are load relations between the modules.
### Term Compilation and Execution

The interpreter traverses the Load Graph and collects all of the available bindings from it. Then it compiles the following term

``` morganey
((\binding-var1 .
((\binding-var2 .
((\binding-var3 .
<...>
((\input . <...>) <input-stream>) // <-- Entry Point term
<...>
)
binding-value3))
binding-value2))
binding-value1)
```

and reduces it. The result of reduction is interpreted as the one of the Church encoded structures and printed on the standard output accordingly.
## REPL

REPL allows the user to input loadings, bindings and free terms. REPL keeps track of all the available bindings in the global context. When a binding or a loading is entered the REPL updates its global context with the new available bindings. Each time the user enters a free term to reduce the REPL contructs the following term

``` morganey
((\binding-var1 .
((\binding-var2 .
((\binding-var3 .
<...>
((\input . <user-entered-term>) <input-stream>)
<...>
)
binding-value3))
binding-value2))
binding-value1)
```

and reduces it. The result of reduction is interpreted as the one of the Church encoded structures and printed on the standard output accordingly. Then the REPL waits for the next command.

---

This semantic is actually pretty close to what I initially wanted from Morganey when I started it.

**Comment by keddelzz** [comment]
I like this proposal! The semantics of a program are now much clearer to me. :)

## 

It has to be semantically verified, that the main binding exists, if there is an explicit entry point to a program. The implementation of the verification should be no problem, though. But It requires a new "compilation phase" after the parser.

**Comment by rexim** [comment]
@keddelzz yep, completely agree with you regarding the entry point verification.

If nobody minds I'm gonna keep it assigned on me. I actually want this to be implemented as soon as possible, because this is gonna define the entire direction of the project. So I willl try to get something done by tomorrow offscreen.

**Comment by keddelzz** [comment]
I don't mind at all!

**Comment by rexim** [comment]
Didn't have a chance to work on this today. Will try to find some time on this week.
