### ISSUE TITLE
Make commands distinguishable from terms in repl

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#83]
As of now, typing `exit` into the repl closes the repl-session. But the name `exit` could also be a valid identifier in Morganey.

It would be nice, if commands would be distinguishable from variables. I propose prefixing commands with a char, that's invalid as a start of an identifier (for example `:`).

**Comment by rexim** [comment]
I remember I even said that on record, but it's pretty hard to find that stream recording at the moment. I said something like if you type `exit` in the REPL, like nothing else, just a bare word `exit`, you most probably want to exit the REPL and not the term `exit`, so we can safely sacrifice this name. :)

But I agree with you. It was just a quick dirty solution and I was kind of joking about that. It's better to prefix such things.

**Comment by keddelzz** [comment]
Can't remember you saying that! I might have missed it. :)

**Comment by keddelzz** [comment]
Which prefix should be used for commands? My suggestions were `:`, `!` or `/`.

@rexim What do you think? Do you have different ideas?

**Comment by rexim** [comment]
As a big fan of Haskell, I like `:` more. :) They use it in ghci.

**Comment by keddelzz** [comment]
`:`is also used in the Scala REPL.

**Comment by rexim** [comment]
Well, looks like Scala developers are fans of Haskell too! :D

**Comment by keddelzz** [comment]
It would be very easy to change `exit` in [this](https://github.com/rexim/Morganey/blob/master/src/main/scala/me/rexim/morganey/Main.scala#L79) line to `:exit`. I suggest including the separation of commands into a collection to the scope of this issue. If commands get separated into a list/map, it could be used in Autocompletion for REPL commands (#87).

**Comment by rexim** [comment]
@keddelzz yeah, sure. Sounds reasonable.
