### ISSUE TITLE
Repl fails on input

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#91]
```
λ> PLUS 2 3
term: (λ m . (λ n . (λ f . (λ x . ((m f) ((n f) x))))))
```

```
λ> a -> b -> a + b
term: a
```

The problem is that in [this line](https://github.com/rexim/Morganey/blob/e2a146b3918d5aabdc11ac35888c64037963a645/src/main/scala/me/rexim/morganey/Main.scala#L38) the parse method is used instead of parseAll.

**Comment by rexim** [comment]
Don't quite understand how `parseAll` would help. The syntax definition literally says that the application should be [enclosed by parenthesis](https://github.com/rexim/Morganey/blob/e2a146b3918d5aabdc11ac35888c64037963a645/kernel/src/main/scala/me/rexim/morganey/syntax/LambdaParser.scala#L68). You will still get an error, because the correct syntax right now is `((PLUS 2) 3)` no matter how you parse it. And fixing that is the scope of #67 IMO.

**Comment by keddelzz** [comment]
`parseAll` requires the parser to look at the whole input, instead of the first correct prefix. You are absolutely right, that this is wrong syntax for an application, but I'd like to get an parser error for that.

**Comment by rexim** [comment]
Ah, very well then. So after this change the REPL gets a bunch of commands per user input instead of one. Just to clarify, how are we gonna evaluate them? Sequentially one by one as if they were entered separately, right?

**Comment by keddelzz** [comment]
No the repl will still get only one command per user input. But it will read the entire input, instead of accepting after the first match.

**Comment by rexim** [comment]
Oh, ok. For some reason I just thought parseAll repeatedly parses input until it parses everything. Looks like I was wrong. Thanks for the explanation! :)

**Comment by keddelzz** [comment]
No problem. :)

**Comment by keddelzz** [comment]
Can I close this issue then? It was fixed with PR #102. :)

**Comment by rexim** [comment]
Ah! Yes, of course! Btw, that's why I always put `Close #<number-of-issue>` in the description of the PR, because GitHub closes the issue automatically once the PR is merged. ;)

Forgot to do that this time, though...

**Comment by keddelzz** [comment]
Nice, to know thank you! I'll add `close #issue` to PRs in the future, too!
