### ISSUE TITLE
Transitive load not working on Windows

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#92]
If a module `A` contains a load-statement, which loads module `B` and `A` gets loaded `B` won't be, yet.

**Comment by rexim** [comment]
I don't quite understand what's the problem here. If I understood you correctly this is exactly how `load prelude` works right now. You load `prelude` and it transitively loads `math.arithmetic`. Could you please clarify this issue?

**Comment by keddelzz** [comment]
If prelude is loaded, it **should** transitively load `math.arithmetic`, but it doesn't.

Maybe I should have said this more clearly. :)

**Comment by rexim** [comment]
Works for me on Linux.

```
λ> SUCC
term: SUCC
λ> load prelude
term: (λ m . (λ n . (λ f . (m (n f)))))
λ> SUCC
term: (λ n . (λ f . (λ x . (f ((n f) x)))))
λ> (SUCC 1)
numbers: 2
λ> 
```

Did you test on Windows?

**Comment by keddelzz** [comment]
Yes, this might be the problem!

**Comment by rexim** [comment]
Thanks! I've modified the title accordingly. :)

**Comment by keddelzz** [comment]
This issue is probably related to #94. So this is a duplicate then.

**Comment by rexim** [comment]
@keddelzz do you want to close it as a duplicate?

**Comment by keddelzz** [comment]
Do I need to do something more to close it as a duplicate? :)

**Comment by rexim** [comment]
Nope, that's enough. Thanks! The most important thing is we have linked this conversation with #94, and now whoever is gonna work on #94 can find it and probably get something useful from it. :)
