### ISSUE TITLE
Autocompletion on Windows

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/Morganey#93]
If

```
?> load <TAB>
```

is entered into the REPL, it autocompletes to

```
load math/     load prelude
```
## 

If

```
?> load math.ari <TAB>
```

is entered into the REPL, it autocompletes to

```
load math/arithmetic
```
## 

Don't mind the `?` instead of the `λ`, the windows terminal can't display it, correctly.

**Comment by rexim** [comment]
Just to clarify, because it was not said explicitly in the issue description. The problem is that on Windows autocomplete suggests the wrong module path separator, right?

**Comment by keddelzz** [comment]
I think so! 
But I don't know why, we both used `File.separatorChar`. Maybe the constant is wrong for some reason.

**Comment by ForNeVeR** [comment]
> Don't mind the `?` instead of the `λ`, the windows terminal can't display it, correctly.

Actually it can. That's the problem of non-unicode API users, and not the general problem of Windows' terminal. With the proper terminal settings and software it's capable of displaying the Unicode characters. I was able to reproduce the issue and currently haven't invented a workaround for Morganey. I'll extract it to separate issue and take a closer look later.

**Comment by keddelzz** [comment]
I think I've found the source of the bug:
The `relativize`-function ([here](https://github.com/rexim/Morganey/blob/88-module-finder-global-context/src/main/scala/me/rexim/morganey/ReplAutocompletion.scala#L77)) always returns a path separated by `/`. `File.separatorChar` returns `/` on linux and `\` on windows. The replace function used [here](https://github.com/rexim/Morganey/blob/88-module-finder-global-context/src/main/scala/me/rexim/morganey/module/ModuleFinder.scala#L14) won't replace path-separators coming from a relative path on windows, which was constructed by the `relativize`-function.

This is my fault, I guess, because I gave the function an invalid input.
