### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#98]
Currently our build fails on Windows because of #93 and we cannot even see that. We need to perform CI on Windows as well. https://www.appveyor.com/ is probably fine.

**Comment by ForNeVeR** [comment]
Feel free to ask for consultation about Appveyor; I'm successfully using it for some of my projects.

**Comment by ForNeVeR** [comment]
A side note: https://www.appveyor.com/docs/build-cache

Other guys tend to use it when installing sbt, see [sbt-native-packager](https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml) as an example. Although I'm not sure if we shouldn't install sbt through choco and preserve choco cache instead. It seems to be a better option.
